<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
// DB読込
use Illuminate\Support\Facades\DB;
// Carbon読込
use Carbon\Carbon;

class JobSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('jobs')->insert([
            [
                'user_id' => '1',
                'genre_id' => '1',
                'area_id' => '13',
                'name' => '企業1',
                'content' => 'コンサート会場の設営、撤去、運営と、グッズ販売、片付けを行ってもらいます。勤務時間は2パターンに分かれていて、お好きな方を選んでいただけますが、人数が少ない方にお願いすることがあります。設営作業や撤去作業など、力仕事も多く、元気な方大歓迎です。',
                'email' => 'campany1@item.com',
                'tel' => '08011112222',
                'salary' => '時給1000～1500円',
                'time' => '①9:00～16:00、②16:00～23:00(休憩1.5h)',
                'shift' => '週1日～',
                'location' => '東京都渋谷区千駄ヶ谷周辺',
                'created_at' => Carbon::now()->__toString(),
                'updated_at' => Carbon::now()->__toString(),
            ],
            [
                'user_id' => '1',
                'genre_id' => '3',
                'area_id' => '3',
                'name' => '企業2',
                'content' => '新しく開店する店のオープニングスタッフを募集します。食事の準備、提供、店内清掃など。お客様1人1人に丁寧に接客できる方を募集します。',
                'email' => 'campany2@item.com',
                'tel' => '08011112222',
                'salary' => '時給950円',
                'time' => '9:00～17:00(休憩1h)',
                'shift' => '週2日～',
                'location' => '東京都港区新橋1丁目',
                'created_at' => Carbon::now()->__toString(),
                'updated_at' => Carbon::now()->__toString(),
            ],
            [
                'user_id' => '1',
                'genre_id' => '2',
                'area_id' => '5',
                'name' => '企業3',
                'content' => '庭園のライトアップイベントです。会場の設営、入場受付、来場者案内、撤去作業をしていただきます。当日の来場者数が見込まれるため、接客経験があり、元気な方歓迎です。',
                'email' => 'campany3@item.com',
                'tel' => '08011112222',
                'salary' => '時給950円',
                'time' => '16:00～22:00',
                'shift' => '2月1日～7日(1日～OK)',
                'location' => '東京都文京区周辺',
                'created_at' => Carbon::now()->__toString(),
                'updated_at' => Carbon::now()->__toString(),
            ],
            [
                'user_id' => '1',
                'genre_id' => '1',
                'area_id' => '1',
                'name' => '企業4',
                'content' => 'コンサート会場の設営、撤去、来場者対応、受付業務、場内アナウンス、グッズ販売、片付けを行ってもらいます。設営作業や撤去作業、来場者対応など、力仕事や長時間の立ち仕事が続くため、体力のある方大歓迎です。',
                'email' => 'campany4@item.com',
                'tel' => '08011112222',
                'salary' => '時給 900円～950円',
                'time' => '16:00～21:00',
                'shift' => '2月7～8日(1日～OK)',
                'location' => '東京都千代田区北の丸公園',
                'created_at' => Carbon::now()->__toString(),
                'updated_at' => Carbon::now()->__toString(),
            ],
            [
                'user_id' => '2',
                'genre_id' => '4',
                'area_id' => '1',
                'name' => '企業5',
                'content' => '食器洗い、ホールスタッフ、受付業務などを担当していただきます。来客者1人1人に丁寧に対応いただける方を募集します。未経験者さん大歓迎です。',
                'email' => 'campany5@item.com',
                'tel' => '08011112222',
                'salary' => '時給1000円～1200円',
                'time' => '17:00～21:00',
                'shift' => '週2日～',
                'location' => '東京都千代田区東京駅周辺',
                'created_at' => Carbon::now()->__toString(),
                'updated_at' => Carbon::now()->__toString(),
            ],
            [
                'user_id' => '2',
                'genre_id' => '2',
                'area_id' => '8',
                'name' => '企業6',
                'content' => 'イベント会場にあるグッズ販売コーナーにて、グッズ販売をしていただける方を募集します。来場者数が多く、お客様に丁寧に接していただける方を募集します。',
                'email' => 'campany6@item.com',
                'tel' => '08011112222',
                'salary' => '時給1200円～1400円',
                'time' => '9:00～17:00の3時間～OK(時間帯は要相談)',
                'shift' => '土、日、祝',
                'location' => '東京都江東区有明',
                'created_at' => Carbon::now()->__toString(),
                'updated_at' => Carbon::now()->__toString(),
            ],
            [
                'user_id' => '2',
                'genre_id' => '2',
                'area_id' => '4',
                'name' => '企業7',
                'content' => '商店街のイベントスタッフを募集します。会場設営、食事作り、食事提供、レジ業務、来場者の案内と対応。普段から人通りが多く、来場者数が見込まれるため、体力のある方大歓迎です。',
                'email' => 'campany7@item.com',
                'tel' => '08011112222',
                'salary' => '時給1,200円～',
                'time' => '①8:00～14:00、②14:00～20:00(休憩1h)',
                'shift' => '2月22日、2月23日(1日～OK)',
                'location' => '東京都新宿区霞ケ丘町',
                'created_at' => Carbon::now()->__toString(),
                'updated_at' => Carbon::now()->__toString(),
            ],
            [
                'user_id' => '2',
                'genre_id' => '2',
                'area_id' => '1',
                'name' => '企業8',
                'content' => 'イベント会場の設営作業、撤去作業をお任せします。会場が広く、力がいる仕事のため、体力のある元気な方歓迎です。未経験、学生さんも大歓迎です。',
                'email' => 'campany8@item.com',
                'tel' => '08011112222',
                'salary' => '時給1,250円',
                'time' => '①9:00～16:00、②16:00～23:00(休憩1h)',
                'shift' => '週2日～',
                'location' => '東京都千代田区九段下駅周辺',
                'created_at' => Carbon::now()->__toString(),
                'updated_at' => Carbon::now()->__toString(),
            ],
            [
                'user_id' => '3',
                'genre_id' => '5',
                'area_id' => '16',
                'name' => '企業9',
                'content' => '店内のグッズ販売コーナーにて、グッズ販売、品出し、接客を担当していただきます。お客様1人1人に笑顔で接客できる方を募集します。学生さん、未経験者さん大歓迎です。',
                'email' => 'campany9@item.com',
                'tel' => '08011112222',
                'salary' => '時給1,200円～',
                'time' => '9:30～20:30、4h～',
                'shift' => '週2日～',
                'location' => '東京都豊島区東池袋',
                'created_at' => Carbon::now()->__toString(),
                'updated_at' => Carbon::now()->__toString(),
            ],
            [
                'user_id' => '3',
                'genre_id' => '6',
                'area_id' => '13',
                'name' => '企業10',
                'content' => '人通りの多い街頭にて、チラシ、ティッシュ配りを担当していただきます。長時間の立ち仕事になるため、体力のある方大歓迎です。',
                'email' => 'campany10@item.com',
                'tel' => '08011112222',
                'salary' => '時給2,000円～',
                'time' => '11:00～18:00、4h～',
                'shift' => '週1日～',
                'location' => '東京都渋谷区渋谷駅前',
                'created_at' => Carbon::now()->__toString(),
                'updated_at' => Carbon::now()->__toString(),
            ],
            [
                'user_id' => '3',
                'genre_id' => '1',
                'area_id' => '13',
                'name' => '企業11',
                'content' => 'コンサート会場の設営、撤去、運営と、グッズ販売、片付けを行ってもらいます。勤務時間は2パターンに分かれていて、お好きな方を選んでいただけますが、人数が少ない方にお願いすることがあります。設営作業や撤去作業など、力仕事も多く、元気な方大歓迎です。',
                'email' => 'campany11@item.com',
                'tel' => '08011112222',
                'salary' => '時給1000～1500円',
                'time' => '①9:00～16:00、②16:00～23:00(休憩1.5h)',
                'shift' => '週1日～',
                'location' => '東京都渋谷区千駄ヶ谷周辺',
                'created_at' => Carbon::now()->__toString(),
                'updated_at' => Carbon::now()->__toString(),
            ],
            [
                'user_id' => '3',
                'genre_id' => '3',
                'area_id' => '3',
                'name' => '企業12',
                'content' => '新しく開店する店のオープニングスタッフを募集します。食事の準備、提供、店内清掃など。お客様1人1人に丁寧に接客できる方を募集します。',
                'email' => 'campany12@item.com',
                'tel' => '08011112222',
                'salary' => '時給950円',
                'time' => '9:00～17:00(休憩1h)',
                'shift' => '週2日～',
                'location' => '東京都港区新橋1丁目',
                'created_at' => Carbon::now()->__toString(),
                'updated_at' => Carbon::now()->__toString(),
            ],
            [
                'user_id' => '4',
                'genre_id' => '2',
                'area_id' => '5',
                'name' => '企業13',
                'content' => '庭園のライトアップイベントです。会場の設営、入場受付、来場者案内、撤去作業をしていただきます。当日の来場者数が見込まれるため、接客経験があり、元気な方歓迎です。',
                'email' => 'campany13@item.com',
                'tel' => '08011112222',
                'salary' => '時給950円',
                'time' => '16:00～22:00',
                'shift' => '2月1日～7日(1日～OK)',
                'location' => '東京都文京区周辺',
                'created_at' => Carbon::now()->__toString(),
                'updated_at' => Carbon::now()->__toString(),
            ],
            [
                'user_id' => '4',
                'genre_id' => '1',
                'area_id' => '1',
                'name' => '企業14',
                'content' => 'コンサート会場の設営、撤去、来場者対応、受付業務、場内アナウンス、グッズ販売、片付けを行ってもらいます。設営作業や撤去作業、来場者対応など、力仕事や長時間の立ち仕事が続くため、体力のある方大歓迎です。',
                'email' => 'campany14@item.com',
                'tel' => '08011112222',
                'salary' => '時給 900円～950円',
                'time' => '16:00～21:00',
                'shift' => '2月7～8日(1日～OK)',
                'location' => '東京都千代田区北の丸公園',
                'created_at' => Carbon::now()->__toString(),
                'updated_at' => Carbon::now()->__toString(),
            ],
            [
                'user_id' => '4',
                'genre_id' => '4',
                'area_id' => '1',
                'name' => '企業15',
                'content' => '食器洗い、ホールスタッフ、受付業務などを担当していただきます。来客者1人1人に丁寧に対応いただける方を募集します。未経験者さん大歓迎です。',
                'email' => 'campany15@item.com',
                'tel' => '08011112222',
                'salary' => '時給1000円～1200円',
                'time' => '17:00～21:00',
                'shift' => '週2日～',
                'location' => '東京都千代田区東京駅周辺',
                'created_at' => Carbon::now()->__toString(),
                'updated_at' => Carbon::now()->__toString(),
            ],
            [
                'user_id' => '4',
                'genre_id' => '2',
                'area_id' => '8',
                'name' => '企業16',
                'content' => 'イベント会場にあるグッズ販売コーナーにて、グッズ販売をしていただける方を募集します。来場者数が多く、お客様に丁寧に接していただける方を募集します。',
                'email' => 'campany16@item.com',
                'tel' => '08011112222',
                'salary' => '時給1200円～1400円',
                'time' => '9:00～17:00の3時間～OK(時間帯は要相談)',
                'shift' => '土、日、祝',
                'location' => '東京都江東区有明',
                'created_at' => Carbon::now()->__toString(),
                'updated_at' => Carbon::now()->__toString(),
            ],
            [
                'user_id' => '5',
                'genre_id' => '2',
                'area_id' => '4',
                'name' => '企業17',
                'content' => '商店街のイベントスタッフを募集します。会場設営、食事作り、食事提供、レジ業務、来場者の案内と対応。普段から人通りが多く、来場者数が見込まれるため、体力のある方大歓迎です。',
                'email' => 'campany17@item.com',
                'tel' => '08011112222',
                'salary' => '時給1,200円～',
                'time' => '①8:00～14:00、②14:00～20:00(休憩1h)',
                'shift' => '2月22日、2月23日(1日～OK)',
                'location' => '東京都新宿区霞ケ丘町',
                'created_at' => Carbon::now()->__toString(),
                'updated_at' => Carbon::now()->__toString(),
            ],
            [
                'user_id' => '5',
                'genre_id' => '2',
                'area_id' => '1',
                'name' => '企業18',
                'content' => 'イベント会場の設営作業、撤去作業をお任せします。会場が広く、力がいる仕事のため、体力のある元気な方歓迎です。未経験、学生さんも大歓迎です。',
                'email' => 'campany18@item.com',
                'tel' => '08011112222',
                'salary' => '時給1,250円',
                'time' => '①9:00～16:00、②16:00～23:00(休憩1h)',
                'shift' => '週2日～',
                'location' => '東京都千代田区九段下駅周辺',
                'created_at' => Carbon::now()->__toString(),
                'updated_at' => Carbon::now()->__toString(),
            ],
            [
                'user_id' => '5',
                'genre_id' => '5',
                'area_id' => '16',
                'name' => '企業19',
                'content' => '店内のグッズ販売コーナーにて、グッズ販売、品出し、接客を担当していただきます。お客様1人1人に笑顔で接客できる方を募集します。学生さん、未経験者さん大歓迎です。',
                'email' => 'campany19@item.com',
                'tel' => '08011112222',
                'salary' => '時給1,200円～',
                'time' => '9:30～20:30、4h～',
                'shift' => '週2日～',
                'location' => '東京都豊島区東池袋',
                'created_at' => Carbon::now()->__toString(),
                'updated_at' => Carbon::now()->__toString(),
            ],
            [
                'user_id' => '5',
                'genre_id' => '6',
                'area_id' => '13',
                'name' => '企業20',
                'content' => '人通りの多い街頭にて、チラシ、ティッシュ配りを担当していただきます。長時間の立ち仕事になるため、体力のある方大歓迎です。',
                'email' => 'campany20@item.com',
                'tel' => '08011112222',
                'salary' => '時給2,000円～',
                'time' => '11:00～18:00、4h～',
                'shift' => '週1日～',
                'location' => '東京都渋谷区渋谷駅前',
                'created_at' => Carbon::now()->__toString(),
                'updated_at' => Carbon::now()->__toString(),
            ],
        ]);
    }
}
